kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: k6-testkube-1
  namespace: testkube
  labels:
    docs: example
spec:
  content:
    git:
      uri: https://github.com/cerebro1/k6-test/
      paths:
      - get.js
  steps:
  - name: Run Tests
    workingDir: /data
    run:
      image: grafana/k6:0.49.0
      env:
      - name: K6_WEB_DASHBOARD
        value: "true"
      - name: K6_WEB_DASHBOARD_EXPORT
        value: k6-test-report.html
      args:
      - run
      - /data/repo/get.js
    artifacts:
      paths:
      - k6-test-report.html
